### ISSUE TITLE
Obtaining hrefID for acsrf

### ISSUE THREAD

**Issue by ambikashri** [psiinon/zaproxy-release#1]
How do we obtain the hrefid for passing it as a parameter  'acsrf/other/genForm/', array('hrefId' => $hrefid, 'apikey' => $apikey). I am running ZAP in daemon mode and performing the spider and active scan using ruby script.

**Comment by psiinon** [comment]
The ACSRF test form is really intended for invoking from the UI : its a manual feature.
However theres nothing to stop you from calling it directly, you just need to know the History Reference Id for the POST request that you want to generate the form for.

**Comment by ambikashri** [comment]
How do we get the history reference ID?

**Comment by psiinon** [comment]
Can you explain your usecase here? On what basis do you want to call this function?
That will determine how you get the history id.

**Comment by ambikashri** [comment]
We are just planning to automate Anti CSRF. So for a login page, I want to to create the anti csrf test form using the api "acsrf/other/genForm/', array('hrefId' => $hrefid, 'apikey' => $apikey)" in order to detect CSRF vulnerabilites to a certain extent.

**Comment by ambikashri** [comment]
So I will spider the site, get the login url and then call the anti csrf api.

**Comment by psiinon** [comment]
You could either search for the relevant message http://zap/UI/search/ or poll through all of the messages http://zap/UI/core/view/messages/ looking for the relevant POST message. You will need to have made the relevant POST, either using the spider or proxying.

**Comment by ambikashri** [comment]
I needed some information after generating the anti csrf test form how to go ahead. So this is the html of my form page
`
<form class="reg gray log-in-half" enctype="application/x-www-form-urlencoded" action="https://secure.test.com/secureLogin" name="login" method="POST">
<input type="hidden" value="1457505010" name="__token_timestamp__">
<input type="hidden" value="1f946eb0703dec132bb1fb3a32f03fb4" name="__token_val__">
<h2>Customer Login</h2>
`
I am doing the below steps.(this is through the UI)
1. Starting ZAP.
2. Adding "_token_timestamp__" and "__token_val__" as anti csrf tokens in the tool in the enable state.
3. Opening the browser and logging into the url i.e, www.test.com
4. Logging out from the url. Close the browser.
5. In the tool i select the appropriate Post request for the url and generate the AntiCSRF test form.
The form contains the below fields
_token_timestamp__
__token_val__
username
password
destination url
- Without doing any changes to the above fields I could successfully login.Also I changed the destination url and I could still login.

My concern is, am I doing the right thing to test CSRF or is there any other way? Also, even without adding the CSRF tokens in the tool I am able to do the above steps. The only difference I see on adding the token is in the History tab i get a tag called "Anti CSRF'

**Comment by psiinon** [comment]
So the idea with the Anti CSRF test page is that it allows you easily play around with all of the fields in a real browser and see what happens.
What I usually look at it whether the anti CSRF token (if any) actually makes any difference.
So use the generated form and try putting different values in the token_val field - if your app rejects all of the requests except ones with a suitably generated token then thats a good indication that its working as required.

**Comment by ambikashri** [comment]
Can we run generate anti csrf test form in daemon mode? Because I am getting the below error on running zap in daemon mode to generate the test form
"751: unexpected token at 'No Implementor'"
|-------------------------------------------

**Comment by psiinon** [comment]
As mentioned in another issue, this is not the real ZAP repo ;) https://github.com/zaproxy/zaproxy
