### ISSUE TITLE
Does anti csrf's generate test form api work in daemon mode?

### ISSUE THREAD

**Issue by ambikashri** [psiinon/zaproxy-release#2]
I am using ZAP 2.4.1 and trying to use the generate anti csrf test form api to test for csrf in daemon mode.
I am using the below api
http://zap/JSON/OTHER/acsrf/other/genForm/?hrefId=351
But it throws the below error
751: unexpected token at 'No Implementor'

**Comment by psiinon** [comment]
This isnt actually the ZAP repo, just a copy I made some time ago ;)
Best to raise ZAP issues here: https://github.com/zaproxy/zaproxy
